[package]
name = "packagename"
version = "0.0.1"
edition = "2024.beta"
# edition = "legacy" to use legacy (pre-2024) Move
# license = ""           # e.g., "MIT", "GPL", "Apache 2.0"
# authors = "John Snow (johnsnow@noemail.com)"]
#published-at = ""

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "main" }
# Revision can be a branch, a tag, and a commit hash; override = true

SupraOracle = { git = "https://github.com/Entropy-Foundation/dora-interface", subdir = "sui/mainnet/supra_holder", rev = "master" }
#SupraOracle = { git = "https://github.com/Entropy-Foundation/dora-interface", subdir = "sui/testnet/supra_holder", rev = "testnet" }

[addresses]
packagename = "0x0"
#sui = "0x2"

#from /mnt/sda3/asui/dora-interface-master/sui/mainnet/supra_holder/Move.toml
SupraOracle = "0x5d8fbbf6f908a4af8c6d072669a462d53e03eb3c1d863bd0359dc818c69ea706"
#SupraOracle = "0xfd8d9e55b7e7ff1f731741297a1499e36351a0760839b046f39fa0cb35147718"
SupraOracleHolder = "0xaa0315f0748c1f24ddb2b45f7939cff40f7a8104af5ccbc4a1d32f870c0b4105"
#SupraOracleHolder = "0x87ef65b543ecb192e89d1e6afeaf38feeb13c3a20c20ce413b29a9cbfbebd570"

[dev-addresses]

[dev-dependencies]
